#!/usr/bin/env bash
# STLIX Hub — form login (username/password page) instead of the browser basic-auth popup.
# Apache mod_auth_form + mod_session_crypto. Same user file as before (/etc/apache2/.htpasswd-stlix):
#   add user:      htpasswd /etc/apache2/.htpasswd-stlix <user>
#   change pass:   htpasswd /etc/apache2/.htpasswd-stlix <user>
#   remove user:   htpasswd -D /etc/apache2/.htpasswd-stlix <user>
# One login covers hub.* and gw.* (cookie domain .stlixvalley.com). Idempotent — re-run any time.
set -euo pipefail
HUB_HOST="${HUB_HOST:-hub.stlixvalley.com}"
GW_HOST="${GW_HOST:-gw.stlixvalley.com}"
COOKIE_DOMAIN="${COOKIE_DOMAIN:-.stlixvalley.com}"
GW_PORT="${GW_PORT:-8010}"
CERT="${CERT:-/etc/letsencrypt/live/hub.153-92-209-190.sslip.io}"
HUB_DIR=/var/www/stlix-hub
HTPASS=/etc/apache2/.htpasswd-stlix
PASS_FILE=/etc/apache2/stlix-session.conf
[ "$(id -u)" = 0 ] || { echo "run as root"; exit 1; }

a2enmod -q session session_cookie session_crypto auth_form request proxy proxy_http headers rewrite ssl >/dev/null
[ -f "$HTPASS" ] || { echo "missing $HTPASS — run deploy.sh first"; exit 1; }
[ -f "$PASS_FILE" ] || { printf 'SessionCryptoPassphrase %s\n' "$(openssl rand -hex 32)" > "$PASS_FILE"; chmod 600 "$PASS_FILE"; }

cat > /etc/apache2/sites-available/stlix-hub.conf <<EOF
# STLIX hub/gw — HTTP: redirect everything to HTTPS
<VirtualHost *:80>
  ServerName ${HUB_HOST}
  ServerAlias ${GW_HOST} hub.153-92-209-190.sslip.io gw.153-92-209-190.sslip.io
  RewriteEngine On
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
EOF

cat > /etc/apache2/sites-available/stlix-hub-le-ssl.conf <<EOF
# STLIX hub/gw — HTTPS with form login (mod_auth_form). Generated by deploy/vps/auth-form.sh
<IfModule mod_ssl.c>

# shared auth block ----------------------------------------------------------
<Macro StlixAuth>
  Session On
  SessionMaxAge 43200
  SessionCookieName stlix_session path=/;domain=${COOKIE_DOMAIN};httponly;secure;samesite=lax
  Include ${PASS_FILE}
  AuthType form
  AuthName "STLIX"
  AuthFormProvider file
  AuthUserFile ${HTPASS}
  AuthFormLoginRequiredLocation "/login.html?to=%{REQUEST_URI}"
  AuthFormLoginSuccessLocation "/"
  AuthFormLogoutLocation "/login.html?out=1"
</Macro>

<Macro StlixAuthEndpoints>
  <Location /login.html>
    Require all granted
  </Location>
  <Location /dologin>
    Use StlixAuth
    SetHandler form-login-handler
    AuthFormLoginRequiredLocation "/login.html?e=1"
    Require all granted
  </Location>
  <Location /logout>
    Use StlixAuth
    SetHandler form-logout-handler
    Require all granted
  </Location>
</Macro>

# HUB — static ---------------------------------------------------------------
<VirtualHost *:443>
  ServerName ${HUB_HOST}
  DocumentRoot ${HUB_DIR}
  Header always set X-Frame-Options SAMEORIGIN
  Header always set X-Content-Type-Options nosniff
  Header always set Referrer-Policy same-origin
  <Directory ${HUB_DIR}>
    Use StlixAuth
    Require valid-user
    Options -Indexes
    AllowOverride None
  </Directory>
  Use StlixAuthEndpoints
  <Location /health>
    Require all granted
    Session Off
  </Location>
  RewriteEngine On
  RewriteRule ^/health$ - [R=200,L]
  SSLCertificateFile ${CERT}/fullchain.pem
  SSLCertificateKeyFile ${CERT}/privkey.pem
  Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>

# GATEWAY — proxy ------------------------------------------------------------
<VirtualHost *:443>
  ServerName ${GW_HOST}
  Alias /login.html ${HUB_DIR}/login.html
  <Directory ${HUB_DIR}>
    Require all granted
  </Directory>
  ProxyPreserveHost On
  ProxyPass /login.html !
  ProxyPass /dologin !
  ProxyPass /logout !
  ProxyPass / http://127.0.0.1:${GW_PORT}/
  ProxyPassReverse / http://127.0.0.1:${GW_PORT}/
  RequestHeader unset Authorization
  <Location />
    Use StlixAuth
    Require valid-user
  </Location>
  Use StlixAuthEndpoints
  <Location /health>
    Session Off
    AuthType None
    Require all granted
  </Location>
  SSLCertificateFile ${CERT}/fullchain.pem
  SSLCertificateKeyFile ${CERT}/privkey.pem
  Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>

# sslip.io aliases → real names (one cookie domain) --------------------------
<VirtualHost *:443>
  ServerName hub.153-92-209-190.sslip.io
  ServerAlias gw.153-92-209-190.sslip.io
  RewriteEngine On
  RewriteCond %{HTTP_HOST} ^hub\. [NC]
  RewriteRule ^ https://${HUB_HOST}%{REQUEST_URI} [R=302,L]
  RewriteRule ^ https://${GW_HOST}%{REQUEST_URI} [R=302,L]
  SSLCertificateFile ${CERT}/fullchain.pem
  SSLCertificateKeyFile ${CERT}/privkey.pem
  Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
EOF

a2enmod -q macro >/dev/null
cp -f "$(dirname "$0")/hub/." -r "$HUB_DIR"/ 2>/dev/null || true
chown -R www-data:www-data "$HUB_DIR"
apache2ctl configtest && systemctl reload apache2
echo "form login enabled → https://${HUB_HOST}/login.html  (users: htpasswd ${HTPASS} <user>)"
